import { PageShell } from "../../components/site/PageShell.jsx";
import ScrollToTop from "../../components/site/ScrollToTop.jsx";
import "../globals.css";
export const metadata = {
  title: {
    default:
      "Hire Top Coder | HireTopCoder — Hire Elite Digital Experts Instantly",
    template: "%s | Hire Top Coder",
  },
  description:
    "HireTopCoder is the curated marketplace to discover, explore and hire elite digital experts in 24 hours. AI-matched, human-vetted.",
  keywords: [
  "HireTopCoder",
  "HireTopCoders",
  "Hire Top Coder",
  "Hire Top Coders",
  "Top",
  "code",
  "coder",
  "coders",
  "Top Coder",
  "Top Coders",
  "GDPR",
  "NDA Protected",
  "Resource",
  "Resources",
  "Hire Developer",
  "Hire Developers",
  "Service",
  "Services",
  "Company",
  "IT",
  "Information Technology",
  "Information Technologies",
  "UI",
  "UX",
  "Designer",
  "Design",
  "UI/UX Design",
  "Full Stack",
  "Development",
  "Full Stack Development",
  "MERN",
  "MERN Stack",
  "MERN Stack Development",
  "MEAN",
  "MEAN Stack",
  "MEAN Stack Development",
  "Mobile",
  "App",
  "Mobile App",
  "Mobile App Development",
  "AI",
  "ML",
  "AI/ML",
  "Ai Agent",
  "Ai Agents",
  "Engineer",
  "AI/ML Engineer",
  "Dev",
  "DevOps",
  "Cloud",
  "DevOps & Cloud",
  "Code",
  "NO-Code",
  "No-Code Development",
  "Graphic",
  "Graphics",
  "Graphic Design",
  "Growth",
  "Marketing",
  "Marketer",
  "Growth Marketing",
  "Hire",
  "Hiring",
  "Hire by Role",
  "Hire UI/UX Designer",
  "Ui/UX Designer",
  "Hire Full Stack Developer",
  "Developer",
  "a Developer",
  "Get a Developer",
  "Get",
  "Hire AI Ml Engineer",
  "Flutter",
  "Flutter Developer",
  "Hire Flutter Developer",
  "Hire Mobile Developer",
  "Mobile Developer",
  "React Native",
  "Hire DevOps Engineer",
  "DevOps Engineer",
  "DevOps Engineers",
  "No-Code developer",
  "Hire No-Code Developer",
  "Hire MERN Stack Developer",
  "MERN Stack Developer",
  "Hire Next Js Developer",
  "Next JS Developer",
  "Next JS Developers",
  "Next",
  "Next Js",
  "Hire React JS Developer",
  "React Js Developer",
  "React Js Developers",
  "Html",
  "Css",
  "javaScript",
  "Tailwind Css",
  "React",
  "React js",
  "Redux",
  "Redux Toolkit",
  "Hire Angular Developer",
  "Angular",
  "Angular Developer",
  "Angular Developers",
  "Hire Wordpress Developer",
  "Wordpress Developers",
  "Wordpress Developer",
  "Wordpress",
  "Hire Ux Developer",
  "Hire Ux Developers",
  "Ux Developer",
  "Ux Developers",
  "Hire Node Js Developer",
  "Hire Node Js Developers",
  "Node Js Developers",
  "Node Js Developer",
  "Node",
  "Node Js",
  "Hire UI Developer",
  "Hire Frontend Developer",
  "Hire Frontend Developers",
  "Frontend Developer",
  "Frontend Developers",
  "Frontend",
  "Hire Backend Developer",
  "Hire Backend Developers",
  "Backend Developer",
  "Backend Developers",
  "Express",
  "Express JS",
  "Redis",
  "AWS",
  "Webflow",
  "Android",
  "Firebase",
  "MongoDB",
  "sql",
  "NoSql",
  "MySql",
  "PostgreSQL",
  "Hire AI Developer",
  "Hire AI Developers",
  "AI Developer",
  "AI Developers",
  "Python",
  "Hire Graphics Designer",
  "Hire Graphics Designers",
  "Graphics Designer",
  "Graphics Designers",
  "Hire Growth Marketers",
  "Hire Growth Marketer",
  "Growth Marketer",
  "Growth Marketers",
  "Remote hire",
  "Remote hiring",
  "Remote MERN Stack Developers Marketplace",
  "Offshore MVP Development Services",
  "Dedicated AI Agent Developers for Hire",
  "SaaS MVP Development in 12 Weeks",
  "Legacy System Modernization Services",
  "Scale Engineering Team in 48 Hours",
  "Remote Developer Hourly Rates 2026",
  "Free Software Project Scoping Template",
  "IT Staff Augmentation vs Dedicated Team Guide",
  "Need Experienced React JS Developer",
  "Hire Next JS Developers Instantly",
  
  "Hire Top 1% React Developer",
  "Hire Dedicated Next JS Developers",
  "Remote MERN Stack Developers Marketplace",
  "Offshore Development Center India",
  "On-demand IT Staff Augmentation Services",
  "Need Experienced Full Stack Developer",
  "SaaS MVP Development Services",
  "Legacy System Modernization Company",
  "Hire Node Js Backend Developers",
  "Python AI ML Engineer for Hire",
  "Scale Engineering Team in 48 Hours",
  "Free Project Scoping Template Download",
  "Offshore Dev Rates 2026 Guide",
  "Dedicated Dev vs Freelancer Comparison",
  "Hire Flutter Mobile App Developer",
  "React Native Mobile Developer Marketplace",
  "DevOps and Cloud Engineering Services",
  "Hire Remote UI UX Designer Teams",
  "SaaS Product Design Journeys",
  "No-Code Webflow Developer for Hire",
  "Hire Graphics Designer Instantly",
  "Growth Marketing Expert for SaaS",
  "Need Experienced React JS Developer",
  "Need IT Staff Augmentation Urgently",
  "MEAN Stack Development Center",
  "AI Agent Workflow Automation Pipelines",
  "Document AI OCR JSON Extraction",
  "Hire Next JS Frontend Developer",
  "Hire Angular Frontend Developers",
  "Hire Wordpress Developer for SaaS",
  "Hire UI Developer Instantly",
  "Hire Android Mobile App Developers",
  "Firebase MongoDB Full Stack Developer",
  "PostgreSQL SQL Developer for Hire",
  "Hire AI Developers for Startups",
  "Remote Hiring Developers Marketplace",
  "Need Team Leader for IT Staff",
  "Get a Developer Cost Estimate",
  "Available Experts for Mobile App Development",
  "Client Satisfaction Engineering Services",
  "Vetted Engineers IT Staff Augmentation",
  "Full Time Dedicated Expert Teams",
  "Investor Ready MVP in 12 Weeks",
  "Add 3-30 Engineers Instantly",
  "Experts Across 50+ Technologies",
  "Full Ride-Booking Mobile App Development",
  "High-Converting Modern User Journeys",
  "Proficient in Modern Web Stacks",
  "Guides Tools and Insights For Hiring",
  "Tech Tips Hiring Guides Industry Trends",
  "Custom AI Agent Developers India",
  "Hire Dedicated Python Developers",
  "Outsource Mobile App Development Center",
  "Hire Top Coders for Enterprise",
  "Hire Remote Backend Developers",
  "Hire Remote Frontend Developers",
  "Express JS Developer for Hire",
  "Tailwind CSS Frontend Developer",
  "Redux Toolkit Expert Developer",
  "UX Developers Marketplace India",
  "Remote Hire Software Engineers",
  "Need Experienced DevOps Engineer",
  "No-Code Shopify and Webflow Developer",
  "Hire Growth Marketers for Tech",
  "Demanded Skills Software Engineers",
  "IT Staff Management Services",
  "Offshore Software Engineering Hiring Insights",
  "Hire Top Coder Marketplace",
  "NDA Protected Remote Software Hiring",
  "GDPR Compliant Tech Talent Marketplace",
  "Hire Full Stack MERN Developers",
  "Hire MEAN Stack Expert Teams",
  "Ai Agent Architecture Pipelines",
  "Hire Remote AWS Cloud Engineer",
  "Need Experienced UI UX Designers",
  "Get a Developer Hourly Rate",
  "Offshore Tech Talent Pricing Calculator",
  "SaaS Product Feature Bento Grid Layout",
  "Kinetic Typography Hero Section Design",
  "Calm Cognitive Clarity UI Design",
  "Spatial Depth Cues UX Prototyping",
  "Three.js React Three Fiber Developer",
  "CSS View Transitions Expert Developer",
  "Web Animations API UI Developer",
  "Variable Fonts Fluid Typography Design",
  "User Context Ambient AI Pipelines",
  "2026 UX Benchmarks Product Audit",
  "Ambient AI Retention Value Guide",
  "UX Revenue Driver Strategy",
  "Accessibility First Design Systems",
  "Bento Grid Layout Feature Showcase",
  "Hire Top Coders Platform",
  "Vetted Offshore Development Teams",
  "Hire Dedicated iOS and Android Developers",
  "Hire Remote Tech Experts Instantly",
  "SaaS Enterprise Tool Design Principles",
  "Intentional Design Minimalism UX",
  "Information Hierarchy Cognitive Priority",
  "Consistent Interaction Patterns SaaS",
  "Micro-interactions Component Design",
  "Thoughtful Empty States UX Strategy",
  "Onboarding Architecture Engineering First Win",
  "First-Value Framework SaaS Onboarding",
  "Progressive Disclosure UX Framework",
  "Stripe Style Onboarding Architecture",
  "Vetted Remote Developers India",
  "Hire Top Coder Core Team",
  "On-Demand Engineering Scale Services",
  "Hire Remote Developers for Startups",
  "Hire Top Developers Vetted Platform",
  "Hire Expert MERN Stack Engineers",
  "Hire Offshore React Native Teams",
  "Hire Remote Next JS Experts",
  "Full Stack Node JS Developer Cost",
  "Hire Mobile App UI UX Designers",
  "Hire Freelance vs Dedicated Developers",
  "Hire Top Developers Globally",
  "Hire Vetted Remote Programmers",
  "Software Project Scoping Templates Free",
  "SaaS Conversion Rate Optimization UX",
  "Hire Dedicated Node JS Programmers",
  "Hire Dedicated Python AI Engineers",
  "Outsource Legacy System Upgrades",
  "Zero Downtime Platform Modernization",
  "Hire UI UX Product Designers",
  "Hire Growth Marketing Growth Hackers",
  "IT Staff Augmentation Pricing 2026",
  "Hire Remote Software Engineers NDA",
  "Secure Remote Hiring Developers",
  "Hire Top Coders for SaaS Development",
  "Hire High-Converting UI Designers",
  "Hire Dedicated Frontend Programmers",
  "Hire Dedicated Backend Programmers",
  "Hire Remote DevOps Cloud Architects",
  "Hire Remote LangGraph AI Developers",
  "Workflow Orchestration Automation Engineers",
  "Structured JSON Output Document AI",
  "OCR Data Extraction Software Engineers",
  "Hire Hybrid Model Recommendation Engineers",
  "RAG Document Citation AI Chatbots",
  "Fallback to Human Support Chatbots",
  "Hire Remote PostgreSQL Database Admins",
  "Hire Remote MongoDB NoSQL Developers",
  "Hire Remote Firebase Backend Engineers",
  "Hire Remote Express JS Web Developers",
  "Hire Remote Flutter Cross-Platform Developers",
  "Hire Remote Tech Talent Within 24 Hours",
  "Hire Top 1% Digital Experts",
  "AI-Matched Human-Vetted Developers",
  "Curated Remote Tech Talent Marketplace",
"Hire Vetted UX Designers",
  "Hire Remote Angular Developers",
  "Hire Expert WordPress Developers",
  "Hire Full Stack Developers India",
  "Hire Dedicated React JS Developers",
  "On-Demand Flutter Developers for Hire",
  "SaaS Enterprise Platform Modernization",
  "Sales CRM Modernization Services",
  "AI Financial Analytics Software Engineering",
  "Next-Gen E-Commerce Stack Scalability",
  "Cloud Native Serverless System Design",
  "Legacy Infrastructure Migration Agency",
  "Outsource Mobile App Development Center",
  "Hire Product Development Expert Teams",
  "Hire Top Coders for Fast-Growing Startups",
  "Adaptive AI Interface Design Services",
  "SaaS UX Design Trends 2026",
  "Premium SaaS Product Development",
  "IT Staff Augmentation within 48 Hours",
  "Remote Developers Marketplace India",
  "Hire Dedicated Engineering Problem Solvers",
  "Remote Hire Developer",
  "Remote Hire Developers",
  "Remote Hiring Developer",
  "Remote Hiring Developers",
  "Remote Developers Marketplace",
  "Remote Developer Marketplace",
  "Developers Marketplace",
  "Developer Marketplace",
  "Technologies",
  "Demanded Skill",
  "Demanded skills",
  "hire IT Staff",
  "IT Staff hire",
  "IT Staff",
  "Need IT Staff",
  "Need Developer",
  "Need Developers",
  "Need IT Engineers",
  "Need Experienced Developer",
  "Need Experienced Developers",
  "Need Experienced Engineer",
  "Need Experienced Engineers",
  "Need IT Professionals",
  "Need IT Professional",
  "Need Team Leader",
  "Need IT Staff Management",
  "Need IT Team",
  "Need IT",
  "IT Staff Hiring",
  "Hiring IT Staff",
  "On-demand IT Staff Augmentation",
  "Dedicated",
  "Team",
  "Expert",
  "Experts",
  "Dedicated Expert",
  "Dedicated Experts",
  "Dedicated Experts Teams",
  "Hire Dedicated Expert Teams",
  "offshore",
  "offshore Development",
  "Development Center",
  "Offshore Development Center",
  "Experts Available",
  "All Time Available",
  "Available Experts",
  "Projects",
  "Client Projects",
  "Personal Projects",
  "Client Satisfaction",
  "Satisfaction",
  "Get a Developer Cost Estimate",
  "Cost",
  "Get A Developer",
  "Cost Estimate",
  "rate",
  "rates",
  "Engineering Hiring Insights",
  "Hiring Insights",
  "Insights",
  "Free Project Scoping Template",
  "Project Scoping",
  "Scoping Template",
  "Scoping Templates",
  "Templates",
  "IT Staff Augmentation",
  "Staff Augmentation",
  "Augmentation",
  "Engineering Services",
  "MVP Development",
  "MVP",
  "Scale Your Engineering team",
  "Scale Engineering Team",
  "Scale Team",
  "scale",
  "Delivery Models",
  "Hiring Guides & FAQs",
  "FAQ",
  "Faqs",
  "blog",
  "case Study",
  "case Studies",
  "Case Study SAAS",
  "SAAS",
  "End-to end digital engineering built around your product goals.",
  "A full-time developer assigned only to your project",
  "Plug vetted engineers into your existing team",
  "Build your own offshore team with our infrastructure",
  "Legacy System Modernization",
  "System Modernization",
  "Investor ready product in 12 weeks",
  "Add 3-30 engineers in 48-72 hours",
  "Experts across 50+ technologies. Cover any stack, any role, any stage.",
  "Full ride-booking app shipped in 8 weeks with real-time scheduling.",
  "Crafting beautiful, high-converting modern user journeys",
  "Proficient in modern web stacks (Python, AI, ML)",
  "Proficient in modern web stacks (MERN, Next.js, MEAN)",
  "Guides, Tools, and insights to help you hire smarter and build faster",
  "Define your project before the first call",
  "Everything you need before hiring",
  "Offshore Dev Rates 2026",
  "Tech tips Hiring guides industry trends",
  "Blog & Insights",
  "Dedicated Dev vs Freelancer - The Real difference",
  "GUIDE 2026",
  "COMPARISON"
],
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // 2. Canonical URL  secure dublicate content
  // metadataBase: new URL("https://www.hiretopcoder.com"), //
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  icons: {
    icon: "/icon.png",
  },
  // metadataBase: new URL("/https://www.hiretopcoder.com"), //Main  Website link
  openGraph: {
    title: "Hire Top Coder",
    description: "HireTopCoder — Hire Elite Digital Experts Instantly",
    url: "", //youtube channel url
    siteName: "Hire Top Coder",
    images: [
      {
        url: "/icon.png",
        width: 1200,
        height: 630,
        alt: "HireTopCoder Logo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Hire Top Coder",
    description:
      "Find the right digital expert instantly. Curated, vetted, ready in hours.",
    creator: "", // @ mention creater
    images: ["/icon.png"],
  },
  // 5. Verification Tokens (Google Search Console & Bing Webmaster Tools के लिए डायरेक्ट इंटीग्रेशन)
  verification: {
    google: "your-google-verification-token", // सर्च कंसोल का टोकन यहाँ डालें
    bing: "your-bing-verification-token",
  },
  // 6. Application/Browser Branding Basics
  icons: {
    icon: "/icon.png",
    shortcut: "/icon.png",
  },

  category: "technology",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head></head>
      <body>
        <PageShell>{children}</PageShell>
        <ScrollToTop />
      </body>
    </html>
  );
}
